from pyspark.sql.types import StructType, StructField, IntegerType, LongType, StringType, ArrayType, TimestampType, BooleanType, DoubleType, MapType

_links_schema = ArrayType(MapType(StringType(), StringType()))

Organization_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("orgId", LongType(), True),
    StructField("tenantName", StringType(), True),
    StructField("tenantCode", StringType(), True),
    StructField("organizationName", StringType(), True),
    StructField("organizationCode", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("organizationExternalIDs", StringType(), True),  
    StructField("customers", StringType(), True),
    StructField("offices", StringType(), True),
    StructField("_links", _links_schema, True),
])

Organization_timestamp_columns = ["dwLastModifiedDateTime"]


Vacancy_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("vacancyId", IntegerType(), True),
    StructField("vacancyType", StringType(), True),
    StructField("jobTitle", StringType(), True),
    StructField("minimumAge", IntegerType(), True),
    StructField("maximumAge", IntegerType(), True),
    StructField("periodOfEligibility", IntegerType(), True),
    StructField("applicationConfirmationMessage", StringType(), True),
    StructField("maximumLocations", IntegerType(), True),
    StructField("securityClearanceRequired", StringType(), True),
    StructField("travelRequired", StringType(), True),
    StructField("payPlanSeriesGrade", StringType(), True),
    StructField("automaticResponseNotification", StringType(), True),
    StructField("vacancyStatus", StringType(), True),
    StructField("cancellationReason", StringType(), True),
    StructField("usaHireCompleteNotification", StringType(), True),
    StructField("usaHireRAReviewNotification", StringType(), True),
    StructField("usaHireRAApprovedNotification", StringType(), True),
    StructField("usaHireRADeniedNotification", StringType(), True),
    StructField("usaHireRequiredNotification", StringType(), True),
    StructField("creationDate", TimestampType(), True),
    StructField("expirationDate", TimestampType(), True),
    StructField("hyperlink", StringType(), True),
    StructField("positionDescriptionTitles", StringType(), True),
    StructField("remoteJobFlag", BooleanType(), True),
    StructField("hasMultipleHurdlesFlag", BooleanType(), True),
    StructField("isSmeEvaluationUsedFlag", BooleanType(), True),
    StructField("candidateInventoryEnabledFlag", BooleanType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("vacancyAppointingAuthorities", StringType(), True),
    StructField("vacancyEligibilities", StringType(), True),
    StructField("vacancyFlags", StringType(), True),
    StructField("vacancyMissionCriticalOccupations", StringType(), True),
    StructField("vacancyPositionDescriptions", StringType(), True),
    StructField("vacancySupportingDocuments", StringType(), True),
    StructField("vacancyTrustDeterminations", StringType(), True),
    StructField("vacancyMetrics", StringType(), True),
    StructField("vacancyExternalIDs", StringType(), True),
    StructField("office", StringType(), True),
    StructField("announcements", StringType(), True),
    StructField("applications", StringType(), True),
    StructField("assessments", StringType(), True),
    StructField("certificates", StringType(), True),
    StructField("customers", StringType(), True),
    StructField("requests", StringType(), True),
    StructField("reviews", StringType(), True),
    StructField("staffingTasks", StringType(), True),
    StructField("_links", _links_schema, True),
])

Vacancy_timestamp_columns = ["creationDate", "expirationDate", "lastModifiedDateTime", "dwLastModifiedDateTime"]

VacancyAppointingAuthority_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("vacancyId", IntegerType(), True),
    StructField("tagId", LongType(), True),
    StructField("appointingAuthority", StringType(), True),
    StructField("appointingAuthorityTagLevel", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True)
])

VacancyAppointingAuthority_timestamp_columns = ["dwLastModifiedDateTime"]

Vacancy_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("vacancyId", IntegerType(), True),
    StructField("vacancyType", StringType(), True),
    StructField("jobTitle", StringType(), True),
    StructField("minimumAge", IntegerType(), True),
    StructField("maximumAge", IntegerType(), True),
    StructField("periodOfEligibility", IntegerType(), True),
    StructField("applicationConfirmationMessage", StringType(), True),
    StructField("maximumLocations", IntegerType(), True),
    StructField("securityClearanceRequired", StringType(), True),
    StructField("travelRequired", StringType(), True),
    StructField("payPlanSeriesGrade", StringType(), True),
    StructField("automaticResponseNotification", StringType(), True),
    StructField("vacancyStatus", StringType(), True),
    StructField("cancellationReason", StringType(), True),
    StructField("usaHireCompleteNotification", StringType(), True),
    StructField("usaHireRAReviewNotification", StringType(), True),
    StructField("usaHireRAApprovedNotification", StringType(), True),
    StructField("usaHireRADeniedNotification", StringType(), True),
    StructField("usaHireRequiredNotification", StringType(), True),
    StructField("creationDate", TimestampType(), True),
    StructField("expirationDate", TimestampType(), True),
    StructField("hyperlink", StringType(), True),
    StructField("positionDescriptionTitles", StringType(), True),
    StructField("remoteJobFlag", BooleanType(), True),
    StructField("hasMultipleHurdlesFlag", BooleanType(), True),
    StructField("isSmeEvaluationUsedFlag", BooleanType(), True),
    StructField("candidateInventoryEnabledFlag", BooleanType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    # Arrays and objects fields...
])

Vacancy_timestamp_columns = ["creationDate", "expirationDate", "lastModifiedDateTime", "dwLastModifiedDateTime"]

VacancyFlag_schema = StructType([
    StructField("tenantId", IntegerType(), nullable=False),
    StructField("vacancyId", IntegerType(), nullable=False),
    StructField("publicFlag", BooleanType(), nullable=False),
    StructField("statusFlag", BooleanType(), nullable=False),
    StructField("internalMeritPromotionFlag", BooleanType(), nullable=False),
    StructField("rnoDataCollectedFlag", BooleanType(), nullable=False),
    StructField("acwaPositionFlag", BooleanType(), nullable=False),
    StructField("applyOnlineEnabledFlag", BooleanType(), nullable=False),
    StructField("ageInformationCollectedFlag", BooleanType(), nullable=False),
    StructField("minimumAgeSetFlag", BooleanType(), nullable=False),
    StructField("maximumAgeSetFlag", BooleanType(), nullable=False),
    StructField("useEffectiveAgeFlag", BooleanType(), nullable=False),
    StructField("underLitigationFlag", BooleanType(), nullable=False),
    StructField("citizenshipScreeningAppliedFlag", BooleanType(), nullable=False),
    StructField("relocationAuthorizedFlag", BooleanType(), nullable=False),
    StructField("supervisoryPositionFlag", BooleanType(), nullable=False),
    StructField("applicantResponseUpdateRestrictedFlag", BooleanType(), nullable=False),
    StructField("automaticResponseFlag", BooleanType(), nullable=False),
    StructField("applicationConfirmationFlag", BooleanType(), nullable=False),
    StructField("allItemsRequiredFlag", BooleanType(), nullable=False),
    StructField("interdisciplinaryFlag", BooleanType(), nullable=False),
    StructField("excludeVeteransFromAgeScreeningFlag", BooleanType(), nullable=False),
    StructField("doNotCollectVeteransPreferenceFlag", BooleanType(), nullable=False),
    StructField("collectServiceComputationDateFlag", BooleanType(), nullable=False),
    StructField("expireApplicationsFlag", BooleanType(), nullable=False),
    StructField("financialDisclosureRequiredFlag", BooleanType(), nullable=False),
    StructField("drugTestingRequiredFlag", BooleanType(), nullable=False),
    StructField("teleworkEligibleFlag", BooleanType(), nullable=False),
    StructField("bargainingUnitPositionFlag", BooleanType(), nullable=False),
    StructField("excludeLandManagementEligiblesFromAgeScreeningFlag", BooleanType(), nullable=False),
    StructField("doNotAgeScreenFlag", BooleanType(), nullable=False),
    StructField("doNotCollectLowestAcceptableGradeFlag", BooleanType(), nullable=False),
    StructField("requireVeteranDocumentsFlag", BooleanType(), nullable=False),
    StructField("requireEligibilityDocumentsFlag", BooleanType(), nullable=False),
    StructField("usaHireNotificationsFlag", BooleanType(), nullable=False),
    StructField("usaHireUsedFlag", BooleanType(), nullable=False),
    StructField("vacancyAnnouncementTypes", StringType(), nullable=False),
    StructField("usaJobsApplicationTotalFlag", BooleanType(), nullable=False),
    StructField("dwLastModifiedDateTime", TimestampType(), nullable=False),
])

VacancyFlag_timestamp_columns = ["dwLastModifiedDateTime"]


TimeToHire_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("requestId", LongType(), True),
    StructField("requestPersonnelActionDate", TimestampType(), True),
    StructField("hiringNeedValidationDate", TimestampType(), True),
    StructField("requestApprovalDate", TimestampType(), True),
    StructField("minJOAReviewSentDate", TimestampType(), True),
    StructField("minJOAReviewReturnedDate", TimestampType(), True),
    StructField("announcementOpenDate", TimestampType(), True),
    StructField("announcementCloseDate", TimestampType(), True),
    StructField("announcementReleasedDate", TimestampType(), True),
    StructField("certificateIssueDate", TimestampType(), True),
    StructField("certificateInitialAuditDate", TimestampType(), True),
    StructField("certificateFinalAuditDate", TimestampType(), True),
    StructField("minCertificateReviewReturnedDate", TimestampType(), True),
    StructField("maxCertificateReviewReturnedDate", TimestampType(), True),
    StructField("minCertificateReviewSentDate", TimestampType(), True),
    StructField("maxCertificateReviewSentDate", TimestampType(), True),
    StructField("completeAssessmentPackageDate", TimestampType(), True),
    StructField("sentTentativeOfferDate", TimestampType(), True),
    StructField("tentativeOfferAcceptedDate", TimestampType(), True),
    StructField("initiateBackgroundInvestigationSecurityClearanceDate", TimestampType(), True),
    StructField("receiveBackgroundInvestigationSecurityClearanceDate", TimestampType(), True),
    StructField("sentFormalOfferDate", TimestampType(), True),
    StructField("formalOfferAcceptedDate", TimestampType(), True),
    StructField("newHireCreationDate", TimestampType(), True),
    StructField("newHireEffectiveDateOfAppointment", TimestampType(), True),
    StructField("newHireProjectedStartDate", TimestampType(), True),
    StructField("newHireActualStartDate", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("hiringNeedValidatedToRequestApproval", IntegerType(), True),
    StructField("overallDaysToHireRequestApprovalDate", IntegerType(), True),
    StructField("requestApprovalToAnnouncementOpen", IntegerType(), True),
    StructField("requestPersonnelActionDateToAnnouncementOpen", IntegerType(), True),
    StructField("requestApprovalToCompleteAssessmentPackage", IntegerType(), True),
    StructField("requestApprovalToJOAReviewSent", IntegerType(), True),
    StructField("joaReviewSentToJOAReviewReturned", IntegerType(), True),
    StructField("joaReviewReturnedToAnnouncementOpen", IntegerType(), True),
    StructField("announcementOpenToClose", IntegerType(), True),
    StructField("announcementCloseToCertificateReviewSentMin", IntegerType(), True),
    StructField("announcementCloseToHire", IntegerType(), True),
    StructField("announcementCloseToCertificateIssued", IntegerType(), True),
    StructField("certificateIssuedToCertificateReturned", IntegerType(), True),
    StructField("certificateReturnedToCertificateAudited", IntegerType(), True),
    StructField("certificateReturnedToTentativeOfferSent", IntegerType(), True),
    StructField("certificateReturnedMaxToTentativeOfferSent", IntegerType(), True),
    StructField("certificateAuditedToTentativeOfferSent", IntegerType(), True),
    StructField("hiringNeedValidatedToTentativeOfferAccepted", IntegerType(), True),
    StructField("backgroundInvestigationandSecurityClearance", IntegerType(), True),
    StructField("tentativeOfferToOfficialOfferSent", IntegerType(), True),
    StructField("officialOfferToEntryOnDuty", IntegerType(), True),
    StructField("requestPersonnelActionDateToEntryOnDuty", IntegerType(), True),
    StructField("overallDaysToHireHiringNeedValidatedDate", IntegerType(), True),
    StructField("timeToHireExternalIDs", StringType(), True),
    StructField("announcement", StructType([]), True),  
    StructField("customer", StructType([]), True),  
    StructField("office", StructType([]), True),  
    StructField("organization", StructType([]), True),  
    StructField("request", StructType([]), True),  
    StructField("vacancy", StructType([]), True),  
    StructField("newHires", StringType(), True),  
    StructField("_links", _links_schema, True),  
])

TimeToHire_timestamp_columns = [
    "requestPersonnelActionDate", "hiringNeedValidationDate", "requestApprovalDate",
    "minJOAReviewSentDate", "minJOAReviewReturnedDate", "announcementOpenDate",
    "announcementCloseDate", "announcementReleasedDate", "certificateIssueDate",
    "certificateInitialAuditDate", "certificateFinalAuditDate",
    "minCertificateReviewReturnedDate", "maxCertificateReviewReturnedDate",
    "minCertificateReviewSentDate", "maxCertificateReviewSentDate",
    "completeAssessmentPackageDate", "sentTentativeOfferDate",
    "tentativeOfferAcceptedDate", "initiateBackgroundInvestigationSecurityClearanceDate",
    "receiveBackgroundInvestigationSecurityClearanceDate", "sentFormalOfferDate",
    "formalOfferAcceptedDate", "newHireCreationDate", "newHireEffectiveDateOfAppointment",
    "newHireProjectedStartDate", "newHireActualStartDate", "dwLastModifiedDateTime"
]

StaffingTask_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("taskId", LongType(), True),
    StructField("taskName", StringType(), True),
    StructField("taskType", StringType(), True),
    StructField("taskTypeId", LongType(), True),
    StructField("purpose", StringType(), True),
    StructField("taskStatus", StringType(), True),
    StructField("ownerEmployeeId", StringType(), True),
    StructField("ownerName", StringType(), True),
    StructField("ownerType", StringType(), True),
    StructField("targetDaysToComplete", IntegerType(), True),
    StructField("actualDaysToComplete", IntegerType(), True),
    StructField("activeDate", TimestampType(), True),
    StructField("dueDate", TimestampType(), True),
    StructField("creationDateTime", TimestampType(), True),
    StructField("completedDateTime", TimestampType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("staffingtaskExternalIDs", StringType(), True),
    StructField("request", StructType([]), True),  
    StructField("vacancy", StructType([]), True),  
    StructField("_links", _links_schema, True),  
])

StaffingTask_timestamp_columns = [
    "activeDate", "dueDate", "creationDateTime", "completedDateTime", 
    "lastModifiedDateTime", "dwLastModifiedDateTime"
]

Review_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("reviewId", IntegerType(), True),
    StructField("reviewName", StringType(), True),
    StructField("owner", StringType(), True),
    StructField("instructions", StringType(), True),
    StructField("dueDate", TimestampType(), True),
    StructField("autoRecallDate", TimestampType(), True),
    StructField("creationDateTime", TimestampType(), True),
    StructField("sentDateTime", TimestampType(), True),
    StructField("returnedDateTime", TimestampType(), True),
    StructField("returnedByName", StringType(), True),
    StructField("recalledDateTime", TimestampType(), True),
    StructField("recallReason", StringType(), True),
    StructField("includesAnnouncementQuestionnaireFlag", BooleanType(), True),
    StructField("includesAnnouncementTextFlag", BooleanType(), True),
    StructField("includesAssessmentFlag", BooleanType(), True),
    StructField("reviewStatus", StringType(), True),
    StructField("lastUpdatedDateTime", TimestampType(), True),
    StructField("reviewType", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("reviewReviewers", StringType(), True),  
    StructField("reviewDocuments", StringType(), True),  
    StructField("reviewExternalIDs", StringType(), True),
    StructField("vacancy", StructType([]), True),  
    StructField("assessments", StringType(), True),  
    StructField("certificates", StringType(), True),  
    StructField("requests", StringType(), True),  
    StructField("_links", _links_schema, True),  
])

Review_timestamp_columns = [
    "dueDate", "autoRecallDate", "creationDateTime", "sentDateTime",
    "returnedDateTime", "recalledDateTime", "lastUpdatedDateTime", "dwLastModifiedDateTime"
]

RequestAppointingAuthority_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("requestId", LongType(), True),
    StructField("tagId", LongType(), True),
    StructField("appointingAuthority", StringType(), True),
    StructField("appointingAuthorityTagLevel", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
])

RequestAppointingAuthority_timestamp_columns = ["dwLastModifiedDateTime"]


Request_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("requestId", LongType(), True),
    StructField("requestNumber", StringType(), True),
    StructField("requestType", StringType(), True),
    StructField("requestSource", StringType(), True),
    StructField("requestStatus", StringType(), True),
    StructField("hiringOrganizationName", StringType(), True),
    StructField("requesterName", StringType(), True),
    StructField("requesterEmail", StringType(), True),
    StructField("requesterPhoneNumber", StringType(), True),
    StructField("approverName", StringType(), True),
    StructField("approverEmail", StringType(), True),
    StructField("approverPhoneNumber", StringType(), True),
    StructField("creationDateTime", TimestampType(), True),
    StructField("submissionDateTime", TimestampType(), True),
    StructField("approvalDateTime", TimestampType(), True),
    StructField("hiringValidationDate", TimestampType(), True),
    StructField("personnelActionDate", TimestampType(), True),
    StructField("cancellationDate", TimestampType(), True),
    StructField("cancellationReason", StringType(), True),
    StructField("bargainingUnitPositionFlag", BooleanType(), True),
    StructField("drugTestingRequiredFlag", BooleanType(), True),
    StructField("financialDisclosureRequiredFlag", BooleanType(), True),
    StructField("relocationAuthorizedFlag", BooleanType(), True),
    StructField("supervisoryPositionFlag", BooleanType(), True),
    StructField("teleworkEligibleFlag", BooleanType(), True),
    StructField("securityClearanceRequired", StringType(), True),
    StructField("travelRequired", StringType(), True),
    StructField("hyperlink", StringType(), True),
    StructField("positionDescriptionNumbers", StringType(), True),
    StructField("positionDescriptionTitles", StringType(), True),
    StructField("remoteJobFlag", BooleanType(), True),
    StructField("requestProcessOwner", StringType(), True),
    StructField("requestProcessOwnerEmail", StringType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("requestAppointingAuthorities", StringType(), True),
    StructField("requestLocations", StringType(), True),
    StructField("requestMissionCriticalOccupations", StringType(), True),
    StructField("requestPositionDescriptions", StringType(), True),
    StructField("requestWorkSchedules", StringType(), True),
    StructField("requestTrustDeterminations", StringType(), True),
    StructField("requestExternalIDs", StringType(), True),
    StructField("customer", StringType(), True),
    StructField("certificateApplications", StringType(), True),
    StructField("newHires", StringType(), True),
    StructField("onboardingTasks", StringType(), True),
    StructField("reviews", StringType(), True),
    StructField("staffingTasks", StringType(), True),
    StructField("vacancies", StringType(), True),
    StructField("_links", _links_schema, True)
])

Request_timestamp_columns = [
    "creationDateTime", "submissionDateTime", "approvalDateTime", "hiringValidationDate",
    "personnelActionDate", "cancellationDate", "lastModifiedDateTime", "dwLastModifiedDateTime"
]


OnboardingTask_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("taskId", LongType(), True),
    StructField("taskName", StringType(), True),
    StructField("taskType", StringType(), True),
    StructField("taskTypeId", LongType(), True),
    StructField("purpose", StringType(), True),
    StructField("taskStatus", StringType(), True),
    StructField("ownerEmployeeId", StringType(), True),
    StructField("ownerName", StringType(), True),
    StructField("ownerType", StringType(), True),
    StructField("targetDaysToComplete", IntegerType(), True),
    StructField("actualDaysToComplete", IntegerType(), True),
    StructField("activeDate", TimestampType(), True),
    StructField("dueDate", TimestampType(), True),
    StructField("creationDateTime", TimestampType(), True),
    StructField("completedDateTime", TimestampType(), True),
    StructField("taskInstructions", StringType(), True),
    StructField("taskResults", StringType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("OnboardingTasksExternalIDs", StringType(), True),  
    StructField("newHire", StringType(), True),  
    StructField("request", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

OnboardingTask_timestamp_columns = [
    "activeDate", "dueDate", "creationDateTime", "completedDateTime", "lastModifiedDateTime", "dwLastModifiedDateTime"
]

NewHireAppointingAuthority_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("tagId", LongType(), True),
    StructField("appointingAuthority", StringType(), True),
    StructField("appointingAuthorityTagLevel", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True)
])

NewHireAppointingAuthority_timestamp_columns = ["dwLastModifiedDateTime"]

Customer_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("customerId", LongType(), True),
    StructField("customerName", StringType(), True),
    StructField("externalName", StringType(), True),
    StructField("agencyCode", StringType(), True),
    StructField("agencyName", StringType(), True),
    StructField("agencyReferenceCode", StringType(), True),
    StructField("departmentCode", StringType(), True),
    StructField("departmentName", StringType(), True),
    StructField("addressLine1", StringType(), True),
    StructField("addressLine2", StringType(), True),
    StructField("addressLine3", StringType(), True),
    StructField("city", StringType(), True),
    StructField("zipCode", StringType(), True),
    StructField("state", StringType(), True),
    StructField("stateAbbreviation", StringType(), True),
    StructField("country", StringType(), True),
    StructField("countryAbbreviation", StringType(), True),
    StructField("phoneNumber", StringType(), True),
    StructField("faxNumber", StringType(), True),
    StructField("opfInstance", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("customerExternalIDs", StringType(), True),  
    StructField("organization", StringType(), True),  
    StructField("announcements", StringType(), True),  
    StructField("offices", StringType(), True),  
    StructField("requests", StringType(), True),  
    StructField("vacancies", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

Customer_timestamp_columns = ["dwLastModifiedDateTime"]


CertificateApplication_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("rankingListId", IntegerType(), True),
    StructField("applicationId", LongType(), True),
    StructField("applicationNumber", StringType(), True),
    StructField("firstName", StringType(), True),
    StructField("middleName", StringType(), True),
    StructField("lastName", StringType(), True),
    StructField("suffix", StringType(), True),
    StructField("applicationName", StringType(), True),
    StructField("startDateTime", TimestampType(), True),
    StructField("priorityDescription", StringType(), True),
    StructField("rankOrder", IntegerType(), True),
    StructField("rating", StringType(), True),
    StructField("recordStatusCode", StringType(), True),
    StructField("recordStatusCodeDescription", StringType(), True),
    StructField("addedFlag", BooleanType(), True),
    StructField("addedDateTime", TimestampType(), True),
    StructField("auditCode", StringType(), True),
    StructField("auditDateTime", TimestampType(), True),
    StructField("certifiedDateTime", TimestampType(), True),
    StructField("eligibilityAdjudicationStatus", StringType(), True),
    StructField("eligibilityClaimed", StringType(), True),
    StructField("eligibleSeries", StringType(), True),
    StructField("eligibilityStartDate", TimestampType(), True),
    StructField("eligibilityEndDate", TimestampType(), True),
    StructField("expiredFlag", BooleanType(), True),
    StructField("veteranPreferenceCode", StringType(), True),
    StructField("veteranPreferenceDescription", StringType(), True),
    StructField("hiredPDNumber", StringType(), True),
    StructField("hiredPositionTitle", StringType(), True),
    StructField("hiredSeries", StringType(), True),
    StructField("hiredSeriesTitle", StringType(), True),
    StructField("hiredCity", StringType(), True),
    StructField("hiredCounty", StringType(), True),
    StructField("hiredState", StringType(), True),
    StructField("hiredCountry", StringType(), True),
    StructField("hiredLocationDescription", StringType(), True),
    StructField("markedAsFavoriteFlag", BooleanType(), True),
    StructField("markedForFollowUpFlag", BooleanType(), True),
    StructField("reorderedFlag", BooleanType(), True),
    StructField("returnStatus", StringType(), True),
    StructField("usaHireCompletedDate", TimestampType(), True),
    StructField("originallySubmittedDateTime", TimestampType(), True),
    StructField("lastSubmittedDateTime", TimestampType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("certificateApplicationApplicant", StringType(), True),  
    StructField("certificateApplicationExternalIDs", StringType(), True),  
    StructField("application", StringType(), True),  
    StructField("certificate", StringType(), True),  
    StructField("newHire", StringType(), True),  
    StructField("request", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

CertificateApplication_timestamp_columns = [
    "startDateTime", "addedDateTime", "auditDateTime", "certifiedDateTime",
    "eligibilityStartDate", "eligibilityEndDate", "usaHireCompletedDate",
    "originallySubmittedDateTime", "lastSubmittedDateTime", "lastModifiedDateTime",
    "dwLastModifiedDateTime"
]

Certificate_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("rankingListId", IntegerType(), True),
    StructField("certificateNumber", StringType(), True),
    StructField("certificateType", StringType(), True),
    StructField("certificateStatus", StringType(), True),
    StructField("certificateOrder", StringType(), True),
    StructField("certificatePriorityOrder", StringType(), True),
    StructField("applicantListName", StringType(), True),
    StructField("signedDateTime", TimestampType(), True),
    StructField("issueDateTime", TimestampType(), True),
    StructField("issuer", StringType(), True),
    StructField("certificateAuditedFlag", BooleanType(), True),
    StructField("initialAuditCompleteDateTime", TimestampType(), True),
    StructField("finalAuditCompleteDateTime", TimestampType(), True),
    StructField("auditedBy", StringType(), True),
    StructField("referMethod", StringType(), True),
    StructField("referMethodNumber", DoubleType(), True),
    StructField("certificateAmendedFlag", BooleanType(), True),
    StructField("certificateCancelledFlag", BooleanType(), True),
    StructField("certificateExpiredFlag", BooleanType(), True),
    StructField("certificateExpirationDate", TimestampType(), True),
    StructField("ctapictapWellQualifiedScore", DoubleType(), True),
    StructField("rankBy", StringType(), True),
    StructField("tieBreaker", StringType(), True),
    StructField("candidateInventoryEnabledFlag", DoubleType(), True),
    StructField("candidateInventoryStartDate", TimestampType(), True),
    StructField("candidateInventoryEndDate", TimestampType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("certificateActionsFilters", StringType(), True),  
    StructField("certificateAssessmentFilters", StringType(), True),
    StructField("certificateCategoryRatingFilters", StringType(), True),
    StructField("certificateCertificationStatusFilters", StringType(), True),
    StructField("certificateEligibilityFilters", StringType(), True),
    StructField("certificateGradeFilters", StringType(), True),
    StructField("certificateLocationFilters", StringType(), True),
    StructField("certificateRSCStatusFilters", StringType(), True),
    StructField("certificateSeriesFilters", StringType(), True),
    StructField("certificateSpecialtyFilters", StringType(), True),
    StructField("certificateVeteransPreferenceFilters", StringType(), True),
    StructField("certificateMetrics", StringType(), True),
    StructField("certificateExternalIDs", StringType(), True),
    StructField("vacancy", StringType(), True),  
    StructField("certificateApplications", StringType(), True),  
    StructField("reviews", StringType(), True),
    StructField("_links", _links_schema, True)
])

Certificate_timestamp_columns = [
    "signedDateTime", "issueDateTime", "initialAuditCompleteDateTime", "finalAuditCompleteDateTime",
    "certificateExpirationDate", "candidateInventoryStartDate", "candidateInventoryEndDate",
    "lastModifiedDateTime", "dwLastModifiedDateTime"
]


Assessment_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("assessmentId", LongType(), True),
    StructField("assessmentName", StringType(), True),
    StructField("assessmentType", StringType(), True),
    StructField("owner", StringType(), True),
    StructField("creationDate", TimestampType(), True),
    StructField("openDate", TimestampType(), True),
    StructField("closeDate", TimestampType(), True),
    StructField("numberOfCompetenciesRated", IntegerType(), True),
    StructField("ratingMethod", StringType(), True),
    StructField("scoringMethod", StringType(), True),
    StructField("acwaAssessmentFlag", BooleanType(), True),
    StructField("usesEqualWeightingFlag", BooleanType(), True),
    StructField("containsScreenOutFlag", BooleanType(), True),
    StructField("containsRatingFlag", BooleanType(), True),
    StructField("passingScore", BooleanType(), True),
    StructField("manualAssessmentMethod", StringType(), True),
    StructField("manualAssessmentMethodDetails", StringType(), True),
    StructField("packageId", LongType(), True),
    StructField("packageSourceOwningOffice", StringType(), True),
    StructField("packageIsTemplateFlag", BooleanType(), True),
    StructField("packageSourceTemplateName", StringType(), True),
    StructField("packageCompleteFlag", BooleanType(), True),
    StructField("packageNotRequiredFlag", BooleanType(), True),
    StructField("packageStatus", StringType(), True),
    StructField("packageLastModifiedDateTime", TimestampType(), True),
    StructField("hurdleId", IntegerType(), True),
    StructField("hurdleName", StringType(), True),
    StructField("smeEvaluationsJustificationRequired", StringType(), True),
    StructField("numberOfRequiredSMEEvaluations", IntegerType(), True),
    StructField("qualityRankingFactorFlag", BooleanType(), True),
    StructField("selectiveFactorFlag", BooleanType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("assessmentCompetencies", StringType(), True),  
    StructField("assessmentExternalIDs", StringType(), True),  
    StructField("vacancy", StringType(), True),  
    StructField("reviews", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

Assessment_timestamp_columns = [
    "creationDate", "openDate", "closeDate", "packageLastModifiedDateTime", "dwLastModifiedDateTime"
]

Application_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("applicationId", LongType(), True),
    StructField("applicantId", LongType(), True),
    StructField("applicationNumber", StringType(), True),
    StructField("applicationOriginallySubmittedDateTime", TimestampType(), True),
    StructField("applicationLastSubmittedDateTime", TimestampType(), True),
    StructField("eligibilityStartDate", TimestampType(), True),
    StructField("eligibilityEndDate", TimestampType(), True),
    StructField("expiredFlag", BooleanType(), True),
    StructField("externalAssessmentStartDate", TimestampType(), True),
    StructField("externalAssessmentEndDate", TimestampType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("applicationStatus", StringType(), True),
    StructField("conflictFlag", BooleanType(), True),
    StructField("conflictResolvedFlag", BooleanType(), True),
    StructField("lowestAcceptableGrade", StringType(), True),
    StructField("markedForFollowUpFlag", BooleanType(), True),
    StructField("recordStatusCode", StringType(), True),
    StructField("recordStatusCodeDescription", StringType(), True),
    StructField("usaHireCompletionDateTime", TimestampType(), True),
    StructField("veteransDocumentSubmissionDate", TimestampType(), True),
    StructField("veteransPreferenceAdjudicated", StringType(), True),
    StructField("veteransPreferenceAdjudicatedDescription", StringType(), True),
    StructField("veteransPreferenceClaimed", StringType(), True),
    StructField("veteransPreferenceClaimedDescription", StringType(), True),
    StructField("candidateInventoryOptInFlag", BooleanType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("applicationApplicant", StringType(), True),
    StructField("applicationAnnouncementItemsAndResponses", StringType(), True),
    StructField("applicationAssessmentItemsAndResponses", StringType(), True),
    StructField("applicationDocuments", StringType(), True),
    StructField("applicationEligibilities", StringType(), True),
    StructField("applicationLocations", StringType(), True),
    StructField("applicationRatings", StringType(), True),
    StructField("applicationRecruitmentSources", StringType(), True),
    StructField("applicationExternalIDs", StringType(), True),
    StructField("office", StringType(), True),
    StructField("vacancy", StringType(), True),
    StructField("certificateApplications", StringType(), True),
    StructField("_links", _links_schema, True)
])

Application_timestamp_columns = [
    "applicationOriginallySubmittedDateTime", "applicationLastSubmittedDateTime",
    "eligibilityStartDate", "eligibilityEndDate", "externalAssessmentStartDate",
    "externalAssessmentEndDate", "lastModifiedDateTime", "usaHireCompletionDateTime",
    "veteransDocumentSubmissionDate", "dwLastModifiedDateTime"
]

Announcement_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("announcementId", LongType(), True),
    StructField("announcementNumber", StringType(), True),
    StructField("announcementStatus", StringType(), True),
    StructField("announcementTemplate", StringType(), True),
    StructField("salaryType", StringType(), True),
    StructField("minimumSalary", DoubleType(), True),
    StructField("maximumSalary", DoubleType(), True),
    StructField("notToExceed", StringType(), True),
    StructField("totalOpenings", StringType(), True),
    StructField("openDate", TimestampType(), True),
    StructField("closeDate", TimestampType(), True),
    StructField("releasedFlag", BooleanType(), True),
    StructField("releasedDateTime", TimestampType(), True),
    StructField("applicationLimitSetFlag", BooleanType(), True),
    StructField("applicationLimit", IntegerType(), True),
    StructField("displayDefaultBenefitsTextFlag", BooleanType(), True),
    StructField("externalContactId", IntegerType(), True),
    StructField("externalContactName", StringType(), True),
    StructField("externalContactEmail", StringType(), True),
    StructField("internalContactId", IntegerType(), True),
    StructField("internalContactName", StringType(), True),
    StructField("internalContactEmail", StringType(), True),
    StructField("usajobsControlNumber", LongType(), True),
    StructField("linkedUSAJOBSControlNumber", LongType(), True),
    StructField("whoMayApply", StringType(), True),
    StructField("whoMayApplyOverrideText", StringType(), True),
    StructField("remoteJobClarificationText", StringType(), True),
    StructField("appointmentTypeOverrideText", StringType(), True),
    StructField("lastModifiedDateTime", TimestampType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("announcementAppointmentTypes", StringType(), True),  
    StructField("announcementHiringPaths", StringType(), True),  
    StructField("announcementLocations", StringType(), True),  
    StructField("announcementWorkSchedules", StringType(), True),  
    StructField("announcementExternalIDs", StringType(), True),  
    StructField("customer", StringType(), True),  
    StructField("office", StringType(), True),  
    StructField("vacancy", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

Announcement_timestamp_columns = ["openDate", "closeDate", "releasedDateTime", "lastModifiedDateTime", "dwLastModifiedDateTime"]

Office_schema = StructType([
    StructField("tenantId", IntegerType(), True),
    StructField("officeId", LongType(), True),
    StructField("officeName", StringType(), True),
    StructField("officeCode", StringType(), True),
    StructField("externalName", StringType(), True),
    StructField("addressLine1", StringType(), True),
    StructField("addressLine2", StringType(), True),
    StructField("addressLine3", StringType(), True),
    StructField("city", StringType(), True),
    StructField("zipCode", StringType(), True),
    StructField("state", StringType(), True),
    StructField("stateAbbreviation", StringType(), True),
    StructField("country", StringType(), True),
    StructField("countryAbbreviation", StringType(), True),
    StructField("phoneNumber", StringType(), True),
    StructField("faxNumber", StringType(), True),
    StructField("dwLastModifiedDateTime", TimestampType(), True),
    StructField("officeExternalIDs", StringType(), True),  
    StructField("organization", StringType(), True),  
    StructField("announcements", StringType(), True),  
    StructField("applications", StringType(), True),  
    StructField("customers", StringType(), True),  
    StructField("newHires", StringType(), True),  
    StructField("vacancies", StringType(), True),  
    StructField("_links", _links_schema, True)  
])

Office_timestamp_columns = ["dwLastModifiedDateTime"]
